version: 2
updates:
  - package-ecosystem: 'npm'
    directories:
      - '/'
    schedule:
      interval: 'weekly'
    versioning-strategy: increase
    assignees:
      - 'pvignau'
    reviewers:
      - 'pvignau'
    groups:
      all:
        patterns:
          - '*'
    ignore:
      - dependency-name: '@storybook/*'
      - dependency-name: 'storybook'
